[tool.poetry]
name = "hw1"
version = "0.1.0"
description = "Python home tasks"
authors = [
    {name = "Stepan Kryzhankov"}
]
requires-python = ">=3.9"


[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
